app: github-node-canvas
stage: dev
component: scf
name: github-node-canvas-scf
inputs:
  name: ${name}
  region: ap-shanghai
  type: web
  image: # 镜像配置
    # registryId: tcr-xxx # 容器镜像服务名称，企业版必须
    imageType: personal # 镜像类型：personal - 个人，enterprise - 企业版，public - 镜像模板
    imageUrl: ${env:IMAGE_URI}
  environment:
    variables:
      NODE_ENV: production
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: ANY
              function:
                type: web
          customDomains:
            - domain: svg.icebreaker.top
              certificateId: ${env:CERTIFICATE_ID}
              isForcedHttps: true
              isDefaultMapping: false
              pathMappingSet:
                - path: /
                  environment: release
              protocols: # 绑定自定义域名的协议类型，默认与服务的前端协议一致。
                - http # 支持http协议
                - https # 支持https协议
